name: Build & Publish NuGet

# on:
#   push:
#     tags:
#       - 'v*'

on: [push]

jobs:
  build:
    permissions:
      id-token: write   # enable GitHub OIDC token issuance for this job

    runs-on: windows-latest

    steps:
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }} # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Display .NET version
        run: dotnet --version

      - name: Restore
        run: dotnet restore WinUSBNet\WinUSBNet.csproj

      - name: Restore Strong Name Key
        run: |
          $base64String = "${{ secrets.STRONG_NAME_KEY }}"
          $bytes = [Convert]::FromBase64String($base64String)
          [System.IO.File]::WriteAllBytes("WinUSBNet\WinUSBNet.snk", $bytes)

      - name: Build
        run: dotnet build WinUSBNet\WinUSBNet.csproj --configuration Release --no-restore

      # - name: Test
      #   run: dotnet test --configuration Release --no-build

      - name: push to NuGet
        # Only push to NuGet if we're building a tag (optional)
        # if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        # Loop through all the packages in the output folder and push them to
        # nuget.org, using the NUGET_API_KEY generated by the previous login step
        run: |
          Get-ChildItem source\nupkg -Filter *.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName `
              --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
              --source https://api.nuget.org/v3/index.json `
              --skip-duplicate
          }
